# .github/workflows/ci_cd.yml
name: "NovaMart CI/CD Pipeline"
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Dependencies
        run: |
          pip install pyspark==4.0.0 pytest pandas pyarrow "numpy<2.0" phonenumbers
      - name: Run Pytest
        run: |
          pytest tests/

  deploy:
    needs: run-tests
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    env:
      HAS_DATABRICKS_SECRET: ${{ secrets.DATABRICKS_HOST != '' }}
    steps:
      - name: Checkout Code
        if: env.HAS_DATABRICKS_SECRET == 'true'
        uses: actions/checkout@v3
      - name: Install Databricks CLI
        if: env.HAS_DATABRICKS_SECRET == 'true'
        run: |
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
      - name: Deploy Asset Bundle (DABs)
        if: env.HAS_DATABRICKS_SECRET == 'true'
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: |
          databricks bundle deploy -t staging